name: 'plain-build-deploy'
on:
  workflow_dispatch: {}
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name != 'examples-generation' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'

      # Step 4 - Builds the site using the latest version of Hugo
      # Also specifies the theme we want to use
      - name: Build
        run: cd site && hugo -b https://deploy-preview-${{ github.event.number }}--startling-truffle-6032f2.netlify.app

      - name: Deploy to Netlify
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install netlify-cli --save-dev
      - run: netlify deploy --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --dir site/public --alias deploy-preview-${{ github.event.number }}--
        ## commit cache
        ## get the public/ dir and upload to netlify preview

        

      