
name: 'examples-generation-test'

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'examples-generation' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build docker with examples test
        run: docker compose up --exit-code-from site
        ## commit cache
        ## get the public/ dir and upload to netlify preview

        

      