name: 'swagger-generation'
on:
  workflow_dispatch: {}
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'swagger-generation' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ## call generateSwagger.py script and commit it to arango main repo

        

      